In [1]:
import pandas as pd
import networkx as nx
import re
import yaml
from itertools import chain
from pathlib import Path
from operator import itemgetter
from collections import defaultdict
import json 
import requests
import matplotlib.pyplot as plt
import pickle

In [2]:
with open('indication_paths.yaml', 'r') as fh:
        ind = yaml.safe_load(fh)

In [3]:
def path_to_tup(path):
    return (path['graph']['drugbank'], path['graph']['disease_mesh'])

def path_to_G(path):
    return nx.node_link_graph(path)                                                                                        

def get_all_paths(path):
    source_id = path['links'][0]['source']                                                                              
    target_ids = list(set([l['target'] for l in path['links']]) - set([l['source'] for l in path['links']]))
    G = path_to_G(path)
    this_paths = list(chain(*[list(nx.all_simple_paths(G, source_id, target_id)) for target_id in target_ids]))         
    return this_paths

def get_id_to_type(G):
    id_to_type = {}
    for n in G.nodes.data():
        id_to_type[n[0]] = n[1]['label']
    return id_to_type

def get_id_to_name(G):
    id_to_name = {}
    for n in G.nodes.data():
        id_to_name[n[0]] = n[1]['name']
    return id_to_name

def add_metaedges(G):
    id_to_type = get_id_to_type(G)
    for e in G.edges:
        G.edges[e]['metaedge'] = id_to_type[e[0]] + ' - ' + e[2] + ' - ' + id_to_type[e[1]]
    return G

def add_meanode_pairs(G):
    id_to_type = get_id_to_type(G)
    for e in G.edges:
        G.edges[e]['mn_pair'] = id_to_type[e[0]] + ' - ' + id_to_type[e[1]]
    return G

def get_targets(G):
    drug = list(G.edges)[0][0]
    targets = []
    for e in G.edges:
        if e[0] == drug:
            targets.append(e[1])
    return targets

def get_target_metaedges(G):
    drug = list(G.edges)[0][0]
    target_mes = []
    if 'metaedge' not in G.edges[list(G.edges)[0]]:
        G = add_metaedges(G)
    
    for e in G.edges:
        if e[0] == drug:
            target_mes.append(G.edges[e]['metaedge'])
    return target_mes

In [4]:
basic_stats = defaultdict(list)
all_metaedges = []
all_parings = []
all_targets = []
unique_metaedges = []
first_edge_type = []
all_nodes = []

id_to_name = {}
id_to_label = {}

for i, p in enumerate(ind):
    drug_id, dis_id = path_to_tup(p)
    paths = get_all_paths(p)
    G = path_to_G(p)
    
    G = add_metaedges(G)
    G = add_meanode_pairs(G)
    
    basic_stats['idx'].append(i)
    basic_stats['id'].append(p['graph']['_id'])
    basic_stats['drug'].append(drug_id)
    basic_stats['disease'].append(dis_id)
    basic_stats['n_nodes'].append(len(G.nodes))
    basic_stats['n_edges'].append(len(G.edges))
    basic_stats['n_paths'].append(len(paths))
    basic_stats['longest_path'].append(max([len(p) for p in paths]))
    basic_stats['shortest_path'].append(max([len(p) for p in paths]))
    basic_stats['metapath'].append(" - ".join([n[1]['label'] for n in G.nodes.data()]))
    basic_stats['metapath_with_edges'].append("".join([re.sub(" - [^-]*$"," - ",e[2]['metaedge']) for e in G.edges.data()])+"Disease")

    
    this_metaedges = [G.edges[e]['metaedge'] for e in G.edges]
    all_metaedges += this_metaedges
    unique_metaedges += list(set(this_metaedges))
    
    all_parings += [G.edges[e]['mn_pair'] for e in G.edges]
    all_targets += get_targets(G)
    first_edge_type += get_target_metaedges(G)
    all_nodes += list(G.nodes)
    
    id_to_label = {**id_to_label, **get_id_to_type(G)}
    id_to_name = {**id_to_name, **get_id_to_name(G)}
    
basic_stats = pd.DataFrame(basic_stats)

In [5]:
basic_stats

,idx,id,drug,disease,n_nodes,n_edges,n_paths,longest_path,shortest_path,metapath,metapath_with_edges
0,0,DB00619_MESH_D015464_1,DB:DB00619,MESH:D015464,3,2,1,3,3,Drug - Protein - Disease,Drug - decreases activity of - Protein - cause...
1,1,DB00619_MESH_D034721_1,DB:DB00619,MESH:D034721,5,5,2,4,4,Drug - Protein - Protein - BiologicalProcess -...,Drug - decreases activity of - Drug - decrease...
2,2,DB00316_MESH_D010146_1,DB:DB00316,MESH:D010146,7,8,3,5,5,Drug - Protein - Protein - Protein - Biologica...,Drug - decreases activity of - Drug - decrease...
3,3,DB00316_MESH_D005334_1,DB:DB00316,MESH:D005334,5,4,1,5,5,Drug - Pathway - GrossAnatomicalStructure - Bi...,Drug - negatively regulates - Pathway - occurs...
4,4,DB00945_MESH_D010146_1,DB:DB00945,MESH:D010146,7,7,2,6,6,Drug - Protein - Protein - BiologicalProcess -...,Drug - decreases activity of - Drug - decrease...
...,...,...,...,...,...,...,...,...,...,...,...
4841,4841,DB01234_MESH_D009404_1,DB:DB01234,MESH:D009404,7,6,1,7,7,Drug - Protein - GeneFamily - GeneFamily - Bio...,Drug - positively regulates - Protein - increa...
4842,4842,DB01234_MESH_C562390_1,DB:DB01234,MESH:C562390,7,6,1,7,7,Drug - Protein - GeneFamily - GeneFamily - Bio...,Drug - positively regulates - Protein - increa...
4843,4843,DB01234_MESH_D000312_1,DB:DB01234,MESH:D000312,4,3,1,4,4,Drug - Protein - BiologicalProcess - Disease,Drug - positively regulates - Protein - negati...
4844,4844,DB01234_MESH_D000224_1,DB:DB01234,MESH:D000224,5,5,2,4,4,Drug - Protein - BiologicalProcess - Biologica...,Drug - positively regulates - Protein - positi...
4845,4845,DB01234_MESH_D000309_1,DB:DB01234,MESH:D000309,4,3,1,4,4,Drug - Protein - BiologicalProcess - Disease,Drug - positively regulates - Protein - positi...

In [6]:
large = basic_stats[(basic_stats['n_nodes'] <= 5) & (basic_stats['n_paths'] == 1)]

In [7]:
large

,idx,id,drug,disease,n_nodes,n_edges,n_paths,longest_path,shortest_path,metapath,metapath_with_edges
0,0,DB00619_MESH_D015464_1,DB:DB00619,MESH:D015464,3,2,1,3,3,Drug - Protein - Disease,Drug - decreases activity of - Protein - cause...
3,3,DB00316_MESH_D005334_1,DB:DB00316,MESH:D005334,5,4,1,5,5,Drug - Pathway - GrossAnatomicalStructure - Bi...,Drug - negatively regulates - Pathway - occurs...
6,6,DB00788_MESH_D010146_1,DB:DB00788,MESH:D010146,5,4,1,5,5,Drug - Protein - ChemicalSubstance - Biologica...,Drug - decreases activity of - Protein - incre...
9,9,DB01610_MESH_D003586_1,DB:DB01610,MESH:D003586,5,4,1,5,5,Drug - ChemicalSubstance - BiologicalProcess -...,Drug - increases abundance of - ChemicalSubsta...
10,10,DB00916_MESH_D018805_1,DB:DB00916,MESH:D018805,5,4,1,5,5,Drug - ChemicalSubstance - BiologicalProcess -...,Drug - increases abundance of - ChemicalSubsta...
...,...,...,...,...,...,...,...,...,...,...,...
4769,4769,DB01590_MESH_D014402_1,DB:DB01590,MESH:D014402,5,4,1,5,5,Protein - Drug - BiologicalProcess - Phenotypi...,Protein - positively regulates - Drug - decrea...
4773,4773,DB00819_MESH_D004832_1,DB:DB00819,MESH:D004832,4,3,1,4,4,Drug - Protein - ChemicalSubstance - Disease,Drug - decreases activity of - Protein - decre...
4780,4780,DB01193_MESH_D006973_1,DB:DB01193,MESH:D006973,5,4,1,5,5,Drug - Protein - ChemicalSubstance - Phenotypi...,Drug - decreases activity of - Protein - posit...
4843,4843,DB01234_MESH_D000312_1,DB:DB01234,MESH:D000312,4,3,1,4,4,Drug - Protein - BiologicalProcess - Disease,Drug - positively regulates - Protein - negati...
4845,4845,DB01234_MESH_D000309_1,DB:DB01234,MESH:D000309,4,3,1,4,4,Drug - Protein - BiologicalProcess - Disease,Drug - positively regulates - Protein - positi...

In [8]:
dmdb_nodes = {}
dmdb_mapping = {}

for index in large['idx']:
    for node in ind[index]['nodes']:
            
        if node['id'].startswith('DB:DB'):
            # Update the node['id'] by replacing 'UniProt' with 'UniProtKB'
            updated_id = node['id'].replace('DB', 'DrugBank:')
#             print('Updated ID: {}   Label: {}'.format(updated_id, node['label']))
            
            # Update the dmdb_nodes dictionary
            dmdb_nodes[updated_id] = node['label']
            dmdb_mapping[node['id']] = updated_id
            
        elif node['id'].startswith('DB:'):
            # Update the node['id'] by replacing 'UniProt' with 'UniProtKB'
            updated_id = node['id'].replace('DB:', 'DrugBank')
#             print('Updated ID: {}   Label: {}'.format(updated_id, node['label']))
            
            # Update the dmdb_nodes dictionary
            dmdb_nodes[updated_id] = node['label']
            dmdb_mapping[node['id']] = updated_id
        else:
            dmdb_nodes[node['id']] = node['label']
            dmdb_mapping[node['id']] = node['id']

In [9]:
mapping = {}
for i in dmdb_nodes: 
    # Handling MESH identifiers
    if i.split(':')[0] == 'MESH' and dmdb_nodes[i] == 'Drug': 
        result = requests.get('https://nodenormalization-sri.renci.org/get_normalized_nodes',
                              params={'curie': i})
        for j in result.json()[i]['equivalent_identifiers']: 
            if j['identifier'].startswith('DRUGBANK'): 
                mapping[i] = j['identifier'].lower().replace(':', '.')
                print(f"MESH Drug Mapped: {mapping[i]}")
                break
        else:
            mapping[i] = i.lower().replace(':', '.')

    elif i.split(':')[0] == 'MESH' and dmdb_nodes[i] == 'Disease': 
        result = requests.get('https://nodenormalization-sri.renci.org/get_normalized_nodes',
                              params={'curie': i})
        try: 
            for j in result.json()[i]['equivalent_identifiers']: 
                if j['identifier'].startswith('MONDO'): 
                    mapping[i] = j['identifier'].lower().replace(':', '.')
                    print(f"MESH Disease Mapped: {mapping[i]}")
                    break
            else:
                mapping[i] = i.lower().replace(':', '.')
        except: 
            continue
                
    elif i.split(':')[0] == 'MESH' and dmdb_nodes[i] == 'ChemicalSubstance': 
        result = requests.get('https://nodenormalization-sri.renci.org/get_normalized_nodes',
                              params={'curie': i})
        try: 
            for j in result.json()[i]['equivalent_identifiers']: 
                if j['identifier'].startswith('DRUGBANK'): 
                    mapping[i] = j['identifier'].lower().replace(':', '.')
                    print(f"ChemicalSubstance Mapped: {mapping[i]}")
                    break
            else:
                mapping[i] = i.lower().replace(':', '.')
        except: 
            continue

    elif i.split(':')[0] == 'MESH' and dmdb_nodes[i] == 'PhenotypicFeature': 
        result = requests.get('https://nodenormalization-sri.renci.org/get_normalized_nodes',
                              params={'curie': i})
        for j in result.json()[i]['equivalent_identifiers']: 
            if j['identifier'].startswith('MONDO'): 
                mapping[i] = j['identifier'].lower().replace(':', '.')
                print(f"PhenotypicFeature Mapped: {mapping[i]}")
                break
        else:
            mapping[i] = i.lower().replace(':', '.')
    
    elif i.split(':')[0] == 'UniProt': 
        mapping[i] = i.lower().replace(':', '.')
        print(f"UniProt Mapped: {mapping[i]}")

    elif i.split(':')[0] == 'HP': 
        # General handling of 'HP' identifiers
        print(f"Processing HP Identifier: {i}")
        if dmdb_nodes[i] == 'Disease':  # Specific HP + Disease condition
            result = requests.get('https://nodenormalization-sri.renci.org/get_normalized_nodes',
                                  params={'curie': i})
            for j in result.json()[i]['equivalent_identifiers']: 
                if j['identifier'].startswith('MONDO'): 
                    mapping[i] = j['identifier'].lower().replace(':', '.')
                    print(f"HP Disease Mapped to MONDO: {mapping[i]}")
                    break
            else:
                mapping[i] = i.lower().replace('hp:', 'hpo.')
        else:  # Generic HP condition
            print(f"Original HP Value: {i}")
            new_value = i.lower().replace('hp:', 'hpo.')
            print(f"Transformed HP Value: {new_value}")
            mapping[i] = new_value
            print(f"HP Mapped: {mapping[i]}")

    elif i.split(':')[0] == 'GO': 
        mapping[i] = i.lower().replace(':', '.')
        print(f"GO Mapped: {mapping[i]}")

    elif i.split(':')[0] == 'UBERON': 
        mapping[i] = i.lower().replace(':', '.')
        print(f"UBERON Mapped: {mapping[i]}")

    else: 
        mapping[i] = i.lower().replace(':', '.')
        print(f"Other Mapped: {mapping[i]}")

MESH Drug Mapped: drugbank.db00619
UniProt Mapped: uniprot.p00519
MESH Disease Mapped: mondo.0011996
MESH Drug Mapped: drugbank.db00316
Other Mapped: reactome.r-hsa-2162123
UBERON Mapped: uberon.0000955
GO Mapped: go.0001659
MESH Drug Mapped: drugbank.db00788
UniProt Mapped: uniprot.p35354
GO Mapped: go.0006954
MESH Drug Mapped: drugbank.db01610
ChemicalSubstance Mapped: drugbank.db01004
GO Mapped: go.0039693
Other Mapped: taxonomy.10358
MESH Disease Mapped: mondo.0005132
MESH Drug Mapped: drugbank.db00916
GO Mapped: go.0003676
Other Mapped: taxonomy.2
MESH Drug Mapped: drugbank.db01060
Other Mapped: tigr.02074
GO Mapped: go.0009252
Other Mapped: taxonomy.1314
MESH Disease Mapped: mondo.0001039
MESH Drug Mapped: drugbank.db00479
UniProt Mapped: uniprot.p0a7s3
GO Mapped: go.0006412
MESH Disease Mapped: mondo.0006670
MESH Drug Mapped: drugbank.db00438
Other Mapped: taxonomy.562
MESH Disease Mapped: mondo.0100338
MESH Drug Mapped: drugbank.db06762
UniProt Mapped: uniprot.q12791
GO Mapped: go.0042311
GO Mapped: go.0008217
MESH Disease Mapped: mondo.0005044
MESH Drug Mapped: drugbank.db01263
UniProt Mapped: uniprot.p10613
ChemicalSubstance Mapped: drugbank.db04038
GO Mapped: go.0009277
MESH Disease Mapped: mondo.0002041
MESH Drug Mapped: drugbank.db08799
UniProt Mapped: uniprot.p35367
GO Mapped: go.0034776
MESH Disease Mapped: mondo.0006004
MESH Drug Mapped: drugbank.db01137
UniProt Mapped: uniprot.p11388
GO Mapped: go.0006260
MESH Disease Mapped: mondo.0006939
MESH Drug Mapped: drugbank.db00814
Other Mapped: interpro.ipr000265
MESH Drug Mapped: drugbank.db00393
Other Mapped: interpro.ipr005446
GO Mapped: go.0006939
MESH Disease Mapped: mondo.0005099
ChemicalSubstance Mapped: drugbank.db01373
MESH Drug Mapped: drugbank.db00342
Processing HP Identifier: HP:0000969
Original HP Value: HP:0000969
Transformed HP Value: hpo.0000969
HP Mapped: hpo.0000969
MESH Disease Mapped: mondo.0006525
MESH Drug Mapped: drugbank.db01048
UniProt Mapped: uniprot.p04585
MESH Disease Mapped: mondo.0005109
MESH Drug Mapped: drugbank.db00717
UniProt Mapped: uniprot.p06401
UniProt Mapped: uniprot.p01148
GO Mapped: go.0032275
MESH Drug Mapped: drugbank.db00748
MESH Disease Mapped: mondo.0005642
MESH Drug Mapped: drugbank.db00066
UniProt Mapped: uniprot.p23945
GO Mapped: go.0030728
MESH Disease Mapped: mondo.0005387
MESH Drug Mapped: drugbank.db01212
UniProt Mapped: uniprot.p0a3m6
Other Mapped: taxonomy.485
MESH Disease Mapped: mondo.0004277
MESH Drug Mapped: drugbank.db02703
UniProt Mapped: uniprot.q81vt3
Other Mapped: taxonomy.1392
MESH Disease Mapped: mondo.0005119
MESH Drug Mapped: drugbank.db00682
UniProt Mapped: uniprot.q9bqb6
GO Mapped: go.0007596
MESH Disease Mapped: mondo.0005279
MESH Drug Mapped: drugbank.db09046
UniProt Mapped: uniprot.p48357
GO Mapped: go.0060612
MESH Disease Mapped: mondo.0006573
MESH Drug Mapped: drugbank.db01332
Other Mapped: taxonomy.573
MESH Disease Mapped: mondo.0030603
MESH Drug Mapped: drugbank.db00455
MESH Disease Mapped: mondo.0011786
MESH Drug Mapped: drugbank.db00935
UniProt Mapped: uniprot.p35348
GO Mapped: go.0042310
MESH Drug Mapped: drugbank.db01174
Other Mapped: interpro.ipr006028
GO Mapped: go.0099536
MESH Disease Mapped: mondo.0005027
MESH Drug Mapped: drugbank.db00281
Other Mapped: interpro.ipr028809
GO Mapped: go.0019233
MESH Drug Mapped: drugbank.db00476
UniProt Mapped: uniprot.p31645
GO Mapped: go.0051610
MESH Disease Mapped: mondo.0002009
MESH Drug Mapped: drugbank.db00366
MESH Drug Mapped: drugbank.db00650
MESH Drug Mapped: drugbank.db00158
MESH Disease Mapped: mondo.0001700
MESH Drug Mapped: drugbank.db01211
UniProt Mapped: uniprot.p44350
Other Mapped: taxonomy.727
MESH Disease Mapped: mondo.0005842
MESH Drug Mapped: drugbank.db00203
UniProt Mapped: uniprot.o76074
ChemicalSubstance Mapped: drugbank.db02315
MESH Disease Mapped: mondo.0005362
MESH Drug Mapped: drugbank.db01155
UniProt Mapped: uniprot.p72525
Other Mapped: taxonomy.1313
MESH Disease Mapped: mondo.0004652
MESH Drug Mapped: drugbank.db00443
UniProt Mapped: uniprot.p04150
UniProt Mapped: uniprot.p47712
MESH Disease Mapped: mondo.0005011
GO Mapped: go.0002553
MESH Drug Mapped: drugbank.db00620
MESH Drug Mapped: drugbank.db00996
UniProt Mapped: uniprot.p54289
GO Mapped: go.0006936
Processing HP Identifier: HP:0012531
Original HP Value: HP:0012531
Transformed HP Value: hpo.0012531
HP Mapped: hpo.0012531
MESH Disease Mapped: mondo.0005391
UniProt Mapped: uniprot.p0ad65
MESH Disease Mapped: mondo.1010128
MESH Drug Mapped: drugbank.db09345
GO Mapped: go.0019227
MESH Drug Mapped: drugbank.db00452
Other Mapped: chebi.18111
Other Mapped: taxonomy.1280
MESH Disease Mapped: mondo.0003085
MESH Drug Mapped: drugbank.db00303
UniProt Mapped: uniprot.p44469
MESH Drug Mapped: drugbank.db06786
MESH Disease Mapped: mondo.0005093
MESH Drug Mapped: drugbank.db01100
UniProt Mapped: uniprot.p14416
GO Mapped: go.0014046
Processing HP Identifier: HP:0100033
Original HP Value: HP:0100033
Transformed HP Value: hpo.0100033
HP Mapped: hpo.0100033
MESH Disease Mapped: mondo.0007661
MESH Drug Mapped: drugbank.db09389
MESH Drug Mapped: drugbank.db08908
UniProt Mapped: uniprot.q14145
UniProt Mapped: uniprot.q16236
GO Mapped: go.0006979
MESH Disease Mapped: mondo.0005301
MESH Drug Mapped: drugbank.db00638
GO Mapped: go.0032099
MESH Disease Mapped: mondo.0002909
MESH Drug Mapped: drugbank.db00344
UniProt Mapped: uniprot.p23975
MESH Drug Mapped: drugbank.db00368
GO Mapped: go.0023041
MESH Drug Mapped: drugbank.db13399
UniProt Mapped: uniprot.p41595
MESH Disease Mapped: mondo.0005149
MESH Drug Mapped: drugbank.db12770
UniProt Mapped: uniprot.p25021
GO Mapped: go.0001696
MESH Disease Mapped: mondo.0007186
MESH Drug Mapped: drugbank.db04938
UniProt Mapped: uniprot.p03372
MESH Disease Mapped: mondo.0001410
MESH Disease Mapped: mondo.0001196
MESH Drug Mapped: drugbank.db00199
Other Mapped: taxonomy.1637
MESH Disease Mapped: mondo.0005828
MESH Drug Mapped: drugbank.db02362
MESH Disease Mapped: mondo.0006594
MESH Drug Mapped: drugbank.db01067
UniProt Mapped: uniprot.q09428
Other Mapped: cl.0000169
UniProt Mapped: uniprot.p01308
MESH Drug Mapped: drugbank.db12212
UniProt Mapped: uniprot.p08588
GO Mapped: go.0045823
MESH Drug Mapped: drugbank.db01106
GO Mapped: go.0004969
MESH Drug Mapped: drugbank.db01418
MESH Drug Mapped: drugbank.db13676
Other Mapped: reactome.r-hsa-390651
MESH Disease Mapped: mondo.0005090
MESH Drug Mapped: drugbank.db00024
UniProt Mapped: uniprot.p16473
UBERON Mapped: uberon.0002046
MESH Disease Mapped: mondo.0015074
MESH Drug Mapped: drugbank.db00524
UniProt Mapped: uniprot.p55017
GO Mapped: go.0055078
MESH Drug Mapped: drugbank.db09142
GO Mapped: go.0032782
MESH Disease Mapped: mondo.0005281
UniProt Mapped: uniprot.p08908
GO Mapped: go.0050795
MESH Drug Mapped: drugbank.db00193
UniProt Mapped: uniprot.p35372
MESH Drug Mapped: drugbank.db00347
UniProt Mapped: uniprot.o43497
GO Mapped: go.0007268
MESH Disease Mapped: mondo.0010826
MESH Drug Mapped: drugbank.db11901
UniProt Mapped: uniprot.p10275
GO Mapped: go.0006351
GO Mapped: go.0008283
MESH Disease Mapped: mondo.0008315
MESH Drug Mapped: drugbank.db05768
ChemicalSubstance Mapped: drugbank.db04160
GO Mapped: go.0030282
Processing HP Identifier: HP:0004349
Original HP Value: HP:0004349
Transformed HP Value: hpo.0004349
HP Mapped: hpo.0004349
MESH Disease Mapped: mondo.0018570
MESH Drug Mapped: drugbank.db00357
UniProt Mapped: uniprot.p11511
MESH Disease Mapped: mondo.0021100
MESH Drug Mapped: drugbank.db06785
UniProt Mapped: uniprot.p30968
UBERON Mapped: uberon.0000007
Other Mapped: interpro.ipr000476
MESH Drug Mapped: drugbank.db00130
Other Mapped: cl.0000584
GO Mapped: go.0050892
MESH Disease Mapped: mondo.0015183
MESH Drug Mapped: drugbank.db01217
GO Mapped: go.0030284
MESH Drug Mapped: drugbank.db03404
UniProt Mapped: uniprot.p13196
Other Mapped: reactome.r-hsa-189451
ChemicalSubstance Mapped: drugbank.db02272
MESH Disease Mapped: mondo.0008294
MESH Drug Mapped: drugbank.db09166
UniProt Mapped: uniprot.p14867
GO Mapped: go.0022851
MESH Disease Mapped: mondo.0005618
MESH Drug Mapped: drugbank.db00446
UniProt Mapped: uniprot.p0a298
Other Mapped: taxonomy.90370
MESH Disease Mapped: mondo.0005619
MESH Drug Mapped: drugbank.db11100
GO Mapped: go.0042060
MESH Disease Mapped: mondo.0006608
UniProt Mapped: uniprot.p19235
GO Mapped: go.0030218
Other Mapped: cl.0000232
MESH Disease Mapped: mondo.0002280
MESH Drug Mapped: drugbank.db00795
UniProt Mapped: uniprot.p09917
GO Mapped: go.0019370
MESH Disease Mapped: mondo.0005101
MESH Drug Mapped: drugbank.db00529
UniProt Mapped: uniprot.p08546
MESH Disease Mapped: mondo.0000878
MESH Drug Mapped: drugbank.db00878
GO Mapped: go.0009274
Other Mapped: taxonomy.837
MESH Disease Mapped: mondo.0005076
MESH Drug Mapped: drugbank.db00059
MESH Disease Mapped: mondo.0004967
MESH Drug Mapped: drugbank.db01201
UniProt Mapped: uniprot.p9wgy7
GO Mapped: go.0032774
Other Mapped: taxonomy.1773
MESH Disease Mapped: mondo.0006052
MESH Drug Mapped: drugbank.db11152
GO Mapped: go.0006915
Other Mapped: taxonomy.10566
MESH Disease Mapped: mondo.0005647
MESH Drug Mapped: drugbank.db12131
UniProt Mapped: uniprot.p54750
GO Mapped: go.0043025
MESH Disease Mapped: mondo.0001627
MESH Drug Mapped: drugbank.db01437
GO Mapped: go.1904862
MESH Disease Mapped: mondo.0013600
MESH Drug Mapped: drugbank.db01213
UniProt Mapped: uniprot.p07327
Other Mapped: reactome.r-hsa-71384
ChemicalSubstance Mapped: drugbank.db01942
MESH Disease Mapped: mondo.0006022
Other Mapped: drugbank..drugbank.11254
MESH Disease Mapped: mondo.0005915
MESH Drug Mapped: drugbank.db11945
UniProt Mapped: uniprot.q9nzq7
GO Mapped: go.0036037
MESH Disease Mapped: mondo.0019210
MESH Drug Mapped: drugbank.db00253
MESH Disease Mapped: mondo.0004577
MESH Disease Mapped: mondo.0006604
MESH Drug Mapped: drugbank.db00630
Other Mapped: cl.0000092
GO Mapped: go.0045453
MESH Disease Mapped: mondo.0008159
MESH Disease Mapped: mondo.0005382
MESH Drug Mapped: drugbank.db01324
GO Mapped: go.0070294
GO Mapped: go.0003092
MESH Drug Mapped: drugbank.db06691
Other Mapped: cl.0000198
Other Mapped: drugbank..drugbank.08822
UniProt Mapped: uniprot.p30556
ChemicalSubstance Mapped: drugbank.db11842
Other Mapped: drugbank..drugbank.09310
GO Mapped: go.0072378
UniProt Mapped: uniprot.p00488
MESH Disease Mapped: mondo.0013187
Other Mapped: drugbank..drugbank.00115
MESH Disease Mapped: mondo.0020696
MESH Disease Mapped: mondo.0020598
GO Mapped: go.005507
MESH Disease Mapped: mondo.0001356
Other Mapped: drugbank..drugbank.00856
GO Mapped: go.0090075
Other Mapped: drugbank..drugbank.06799
ChemicalSubstance Mapped: drugbank.db03843
GO Mapped: go.0030164
Other Mapped: chebi.29034
Other Mapped: chebi.18367
MESH Disease Mapped: mondo.0000328
MESH Drug Mapped: drugbank.db12498
UniProt Mapped: uniprot.p51679
GO Mapped: go.0038152
GO Mapped: go.0042098
MESH Disease Mapped: mondo.0000430
MESH Drug Mapped: drugbank.db00421
UniProt Mapped: uniprot.p08235
ChemicalSubstance Mapped: drugbank.db04630
MESH Disease Mapped: mondo.0003009
MESH Drug Mapped: drugbank.db00216
UniProt Mapped: uniprot.p28221
GO Mapped: go.0004993
MESH Disease Mapped: mondo.0005277
UniProt Mapped: uniprot.p28222
UniProt Mapped: uniprot.p28223
MESH Drug Mapped: drugbank.db12459
UniProt Mapped: uniprot.p11387
GO Mapped: go.0003677
MESH Disease Mapped: mondo.0005233
MESH Disease Mapped: mondo.0008170
MESH Drug Mapped: drugbank.db00655
MESH Disease Mapped: mondo.0005298
MESH Drug Mapped: drugbank.db01294
ChemicalSubstance Mapped: drugbank.db00936
MESH Disease Mapped: mondo.0002268
MESH Drug Mapped: drugbank.db09010
UniProt Mapped: uniprot.q13510
GO Mapped: go.0016049
UBERON Mapped: uberon.0001155
MESH Disease Mapped: mondo.0005401
UniProt Mapped: uniprot.p0dtd1
MESH Disease Mapped: mondo.0100096
Other Mapped: drugbank..drugbank.00007
GO Mapped: go.0005183
GO Mapped: go.0006703
MESH Disease Mapped: mondo.0005133
MESH Drug Mapped: drugbank.db00250
MESH Disease Mapped: mondo.0015614
MESH Drug Mapped: drugbank.db04865
UniProt Mapped: uniprot.p39023
UniProt Mapped: uniprot.a9uf02
MESH Drug Mapped: drugbank.db08902
UniProt Mapped: uniprot.p13423
MESH Disease Mapped: mondo.0016595
MESH Drug Mapped: drugbank.db00283
GO Mapped: go.0002441
MESH Disease Mapped: mondo.0005492
MESH Drug Mapped: drugbank.db00360
UniProt Mapped: uniprot.p00439
GO Mapped: go.0004505
Other Mapped: chebi.28044
MESH Disease Mapped: mondo.0009861
MESH Drug Mapped: drugbank.db00626
Other Mapped: chebi.17047
GO Mapped: go.0009273
MESH Disease Mapped: mondo.0004795
MESH Disease Mapped: mondo.0020283
UniProt Mapped: uniprot.p62594
GO Mapped: go.0030655
UniProt Mapped: uniprot.p0ad63
Other Mapped: interpro.ipr012338
MESH Disease Mapped: mondo.0024313
Other Mapped: taxonomy.1763
MESH Disease Mapped: mondo.0005649
MESH Drug Mapped: drugbank.db12319
UniProt Mapped: uniprot.q96s37
GO Mapped: go.0015747
GO Mapped: go.0097744
MESH Disease Mapped: mondo.0005393
MESH Drug Mapped: drugbank.db01579
Processing HP Identifier: HP:0004396
Original HP Value: HP:0004396
Transformed HP Value: hpo.0004396
HP Mapped: hpo.0004396
MESH Disease Mapped: mondo.0011122
UniProt Mapped: uniprot.p35368
MESH Drug Mapped: drugbank.db00313
Other Mapped: interpro.ipr002587
UniProt Mapped: uniprot.p29218
MESH Disease Mapped: mondo.0004985
Other Mapped: reactome.r-hsa-211976
Other Mapped: mesh.d008560
GO Mapped: go.0099611
Other Mapped: reactome.r-hsa-556833
MESH Drug Mapped: drugbank.db00758
UniProt Mapped: uniprot.q9h244
GO Mapped: go.0070527
MESH Disease Mapped: mondo.0005542
MESH Disease Mapped: mondo.0006809
Other Mapped: drugbank..drugbank.08873
UniProt Mapped: uniprot.b0b3c9
Other Mapped: taxonomy.11103
MESH Disease Mapped: mondo.0005354
GO Mapped: go.0006508
MESH Drug Mapped: drugbank.db01282
MESH Disease Mapped: mondo.0008300
MESH Drug Mapped: drugbank.db00835
MESH Drug Mapped: drugbank.db05381
GO Mapped: go.0043114
MESH Disease Mapped: mondo.0005324
Other Mapped: interpro.ipr000995
MESH Drug Mapped: drugbank.db02659
UBERON Mapped: uberon.0002423
MESH Disease Mapped: mondo.0004868
MESH Disease Mapped: mondo.0012672
GO Mapped: go.0030432
MESH Disease Mapped: mondo.0002203
MESH Drug Mapped: drugbank.db09552
UniProt Mapped: uniprot.q59r99
GO Mapped: go.0030641
Other Mapped: taxonomy.5476
MESH Drug Mapped: drugbank.db12159
UniProt Mapped: uniprot.p24394
Other Mapped: reactome.r-hsa-6785807
GO Mapped: go.0042092
MESH Disease Mapped: mondo.0004980
MESH Drug Mapped: drugbank.db00051
UniProt Mapped: uniprot.p01375
Other Mapped: reactome.r-hsa-75893
MESH Disease Mapped: mondo.0006559
MESH Disease Mapped: mondo.0008383
MESH Disease Mapped: mondo.0011849
MESH Disease Mapped: mondo.0005306
MESH Drug Mapped: drugbank.db14638
MESH Disease Mapped: mondo.0005644
MESH Drug Mapped: drugbank.db12523
MESH Disease Mapped: mondo.0024332
MESH Drug Mapped: drugbank.db05812
GO Mapped: go.0060767
MESH Drug Mapped: drugbank.db00285
MESH Disease Mapped: mondo.0005383
GO Mapped: go.0051620
MESH Disease Mapped: mondo.0001247
UniProt Mapped: uniprot.q01959
GO Mapped: go.0090494
MESH Drug Mapped: drugbank.db00543
MESH Disease Mapped: mondo.0002050
UniProt Mapped: uniprot.p21728
GO Mapped: go.0051584
MESH Drug Mapped: drugbank.db06817
UniProt Mapped: uniprot.q7zjm1
GO Mapped: go.0044823
Other Mapped: taxonomy.11676
MESH Drug Mapped: drugbank.db04932
MESH Drug Mapped: drugbank.db01240
GO Mapped: go.0044557
MESH Disease Mapped: mondo.0019514
ChemicalSubstance Mapped: drugbank.db00917
MESH Drug Mapped: drugbank.db01080
UniProt Mapped: uniprot.p80404
GO Mapped: go.0009450
ChemicalSubstance Mapped: drugbank.db02530
MESH Disease Mapped: mondo.0018097
MESH Drug Mapped: drugbank.db00488
GO Mapped: go.0006305
Other Mapped: cl.0001063
Other Mapped: chebi.73080
MESH Drug Mapped: drugbank.db00383
UniProt Mapped: uniprot.p20309
GO Mapped: go.0001699
MESH Disease Mapped: mondo.0004247
MESH Drug Mapped: drugbank.db00550
UniProt Mapped: uniprot.p07202
GO Mapped: go.0006590
MESH Disease Mapped: mondo.0004425
MESH Disease Mapped: mondo.0006996
MESH Drug Mapped: drugbank.db01087
GO Mapped: go.0042775
Other Mapped: taxonomy.5855
MESH Disease Mapped: mondo.0005921
Other Mapped: drugbank..drugbank.01340
UniProt Mapped: uniprot.p12821
MESH Drug Mapped: drugbank.db06756
MESH Disease Mapped: mondo.0004737
Processing HP Identifier: HP:0012072
Original HP Value: HP:0012072
Transformed HP Value: hpo.0012072
HP Mapped: hpo.0012072
MESH Disease Mapped: mondo.0001882
MESH Disease Mapped: mondo.0006032
MESH Drug Mapped: drugbank.db06770
Other Mapped: taxonomy.52283
MESH Drug Mapped: drugbank.db00999
MESH Drug Mapped: drugbank.db06616
MESH Disease Mapped: mondo.0006115
MESH Drug Mapped: drugbank.db09321
Other Mapped: taxonomy.4751
MESH Disease Mapped: mondo.0005984
MESH Disease Mapped: mondo.0000879
GO Mapped: go.0043303
GO Mapped: go.0001821
MESH Drug Mapped: drugbank.db00136
UniProt Mapped: uniprot.p11473
GO Mapped: go.0060558
GO Mapped: go.0055074
MESH Drug Mapped: drugbank.db00165
UniProt Mapped: uniprot.o00764
GO Mapped: go.0008478
Other Mapped: chebi.18405
MESH Disease Mapped: mondo.0004574
MESH Drug Mapped: drugbank.db09304
Other Mapped: interpro.ipr002231
GO Mapped: go.0001820
GO Mapped: go.0099153
GO Mapped: go.0005886
MESH Disease Mapped: mondo.0002508
MESH Drug Mapped: drugbank.db11574
UniProt Mapped: uniprot.q5l478
GO Mapped: go.0019079
GO Mapped: go.0019068
MESH Drug Mapped: drugbank.db09078
Other Mapped: interpro.ipr016248
Other Mapped: cl.0001064
MESH Disease Mapped: mondo.0005075
UniProt Mapped: uniprot.p16234
UniProt Mapped: uniprot.p10721
UniProt Mapped: uniprot.p07949
Other Mapped: interpro.ipr009135
GO Mapped: go.0001525
MESH Disease Mapped: mondo.0005034
MESH Disease Mapped: mondo.0005086
MESH Drug Mapped: drugbank.db08865
UniProt Mapped: uniprot.q9um73
UniProt Mapped: uniprot.p08922
MESH Drug Mapped: drugbank.db00508
MESH Drug Mapped: drugbank.db00988
MESH Drug Mapped: drugbank.db00404
MESH Disease Mapped: mondo.0011918
Processing HP Identifier: HP:0000739
Original HP Value: HP:0000739
Transformed HP Value: hpo.0000739
HP Mapped: hpo.0000739
MESH Drug Mapped: drugbank.db00921
UniProt Mapped: uniprot.p41145
MESH Drug Mapped: drugbank.db08998
Processing HP Identifier: HP:0000716
Original HP Value: HP:0000716
Transformed HP Value: hpo.0000716
HP Mapped: hpo.0000716
MESH Drug Mapped: drugbank.db04861
Processing HP Identifier: HP:0032263
Original HP Value: HP:0032263
Transformed HP Value: hpo.0032263
HP Mapped: hpo.0032263
MESH Drug Mapped: drugbank.db01113
UniProt Mapped: uniprot.q07343
ChemicalSubstance Mapped: drugbank.db02527
MESH Disease Mapped: mondo.0005294
MESH Drug Mapped: drugbank.db00385
MESH Disease Mapped: mondo.0004987
UniProt Mapped: uniprot.p30559
GO Mapped: go.0070474
MESH Drug Mapped: drugbank.db00829
GO Mapped: go.0016917
GO Mapped: go.0061534
MESH Drug Mapped: drugbank.db09081
GO Mapped: go.0022900
GO Mapped: go.0005747
MESH Disease Mapped: mondo.0010788
MESH Drug Mapped: drugbank.db01577
GO Mapped: go.0004936
GO Mapped: go.0032100
MESH Drug Mapped: drugbank.db06702
GO Mapped: go.0014832
GO Mapped: go.0060073
MESH Drug Mapped: drugbank.db00553
Processing HP Identifier: HP:0031377
Original HP Value: HP:0031377
Transformed HP Value: hpo.0031377
HP Mapped: hpo.0031377
MESH Disease Mapped: mondo.0000607
Other Mapped: cl.0000148
GO Mapped: go.0043473
MESH Disease Mapped: mondo.0008661
MESH Drug Mapped: drugbank.db00747
MESH Drug Mapped: drugbank.db00865
UniProt Mapped: uniprot.p14778
GO Mapped: go.0004908
MESH Disease Mapped: mondo.0016168
MESH Drug Mapped: drugbank.db00065
MESH Drug Mapped: drugbank.db00423
MESH Drug Mapped: drugbank.db00496
MESH Drug Mapped: drugbank.db09041
UniProt Mapped: uniprot.q9hgt2
Other Mapped: taxonomy.5551
MESH Disease Mapped: mondo.0001628
MESH Drug Mapped: drugbank.db01193
ChemicalSubstance Mapped: drugbank.db00668
Processing HP Identifier: HP:0001649
Original HP Value: HP:0001649
Transformed HP Value: hpo.0001649
HP Mapped: hpo.0001649
MESH Drug Mapped: drugbank.db00964
UniProt Mapped: uniprot.p08913
UBERON Mapped: uberon.0001796
Processing HP Identifier: HP:0007906

In [10]:
modified_data = {key: '.'.join([part.split('.')[0], ''.join([x.upper() for x in part.split('.')[1]])]) for key, part in mapping.items()}

In [11]:
large_idx = list(large['idx'])

In [14]:
G = pickle.load(open('graph_v3.pkl', 'rb'))

In [15]:
large_idx = list(large['idx'])
for index in large['idx']:
    for node in ind[index]['nodes']:
        try: 
#             print(dmdb_mapping[node['id']])
#             print(modified_data[dmdb_mapping[node['id']]])
            if modified_data[dmdb_mapping[node['id']]] not in G.nodes: 
                print('Node not in G:', modified_data[dmdb_mapping[node['id']]])
                large_idx.remove(index)
                break
        except: 
            large_idx.remove(index)
            print('Node not in mapping:', node['id'])
            break

Node not in G: uberon.0000955
Node not in G: mesh.D011453
Node not in G: taxonomy.10358
Node not in G: mesh.C029371
Node not in G: tigr.02074
Node not in G: taxonomy.2
Node not in G: tigr.02074
Node not in G: taxonomy.562
Node not in G: mesh.D011453
Node not in G: mesh.C007852
Node not in G: mesh.C066928
Node not in G: mesh.D008595
Node not in G: taxonomy.485
Node not in G: uniprot.Q81VT3
Node not in G: mesh.D014812
Node not in G: tigr.02074
Node not in G: mesh.D015508
Node not in G: interpro.IPR028809
Node not in G: uniprot.P44350
Node not in G: taxonomy.1313
Node not in G: mesh.C106301
Node not in G: mesh.D015378
Node not in G: interpro.IPR028809
Node not in G: chebi.18111
Node not in G: taxonomy.727
Node not in G: mesh.D008595
Node not in G: mesh.D004967
Node not in mapping: MESH:D012338
Node not in G: cl.0000169
Node not in G: mesh.D013610
Node not in G: mesh.D014812
Node not in G: mesh.C039979
Node not in G: mesh.D010146
Node not in G: drugbank.DB05768
Node not in G: mesh.D004967
Node not in mapping: MESH:D010062
Node not in G: cl.0000584
Node not in G: mesh.D004967
Node not in G: uniprot.P0A298
Node not in G: mesh.C555712
Node not in G: taxonomy.10358
Node not in G: taxonomy.837
Node not in G: mesh.D001216
Node not in G: taxonomy.1773
Node not in G: taxonomy.10566
Node not in G: mesh.C042131
Node not in G: drugbank.
Node not in G: cl.0000092
Node not in G: cl.0000092
Node not in G: cl.0000198
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: mesh.C025314
Node not in G: mesh.D004967
Node not in G: drugbank.
Node not in G: taxonomy.1392
Node not in G: mesh.D011537
Node not in G: mesh.D012912
Node not in G: chebi.28044
Node not in G: chebi.17047
Node not in G: chebi.18111
Node not in G: chebi.18111
Node not in G: chebi.18111
Node not in G: mesh.C043265
Node not in G: mesh.C043265
Node not in G: mesh.C043265
Node not in G: mesh.C043265
Node not in G: mesh.C043265
Node not in G: mesh.D033461
Node not in G: mesh.D007294
Node not in G: mesh.D008560
Node not in G: mesh.D008560
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: mesh.D011537
Node not in G: mesh.D011537
Node not in G: uberon.0002423
Node not in G: uniprot.Q59R99
Node not in G: mesh.D001171
Node not in G: taxonomy.11676
Node not in G: cl.0001063
Node not in G: chebi.73080
Node not in G: mesh.D005744
Node not in G: taxonomy.5855
Node not in G: drugbank.
Node not in G: mesh.D006710
Node not in G: taxonomy.52283
Node not in G: mesh.D004487
Node not in G: mesh.C009927
Node not in G: taxonomy.4751
Node not in G: taxonomy.4751
Node not in G: mesh.D011537
Node not in G: mesh.D006996
Node not in G: chebi.18405
Node not in G: taxonomy.2
Node not in G: taxonomy.11103
Node not in G: taxonomy.11103
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: cl.0001064
Node not in G: mesh.D014839
Node not in G: mesh.D009325
Node not in G: mesh.D059350
Node not in G: cl.0001063
Node not in G: mesh.D006473
Node not in G: mesh.D009128
Node not in G: mesh.D053202
Node not in G: mesh.D004247
Node not in G: cl.0000148
Node not in G: mesh.D005744
Node not in G: mesh.D053590
Node not in G: mesh.D009128
Node not in G: mesh.D053202
Node not in G: taxonomy.5551
Node not in G: mesh.D018879
Node not in G: uberon.0001796
Node not in G: hpo.0031377
Node not in G: mesh.D033461
Node not in G: mesh.D005963
Node not in G: mesh.D006947
Node not in G: mesh.D006996
Node not in G: chebi.47774
Node not in G: mesh.D000787
Node not in G: mesh.D000787
Node not in G: mesh.D019584
Node not in G: mesh.C016671
Node not in G: mesh.C016671
Node not in G: mesh.C016671
Node not in G: mesh.D006470
Node not in G: mesh.D005871
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D033461
Node not in G: drugbank.
Node not in G: mesh.D006996
Node not in G: taxonomy.550
Node not in G: taxonomy.287
Node not in G: mesh.C587012
Node not in G: chebi.27226
Node not in G: chebi.21241
Node not in G: chebi.16933
Node not in G: taxonomy.5833
Node not in G: pfam.PF06589
Node not in G: cl.0000542
Node not in G: chebi.15940
Node not in G: mesh.D018168
Node not in G: taxonomy.1392
Node not in G: mesh.D001792
Node not in G: mesh.D009496
Node not in G: mesh.D005744
Node not in G: uberon.0002206
Node not in G: taxonomy.11676
Node not in G: drugbank.
Node not in G: mesh.C537592
Node not in G: mesh.D004487
Node not in G: taxonomy.1773
Node not in G: mesh.D020738
Node not in G: mesh.D020738
Node not in G: mesh.D015878
Node not in G: taxonomy.5855
Node not in G: taxonomy.5833
Node not in G: mesh.D013455
Node not in G: chebi.18243
Node not in G: drugbank.
Node not in G: mesh.C587014
Node not in G: taxonomy.1773
Node not in G: mesh.D011628
Node not in G: mesh.D011628
Node not in G: taxonomy.1280
Node not in G: taxonomy.2
Node not in G: taxonomy.12721
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: drugbank.
Node not in G: chebi.15940
Node not in G: uniprot.P03120
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: mesh.D013226
Node not in G: mesh.D008595
Node not in G: mesh.D008595
Node not in G: mesh.D019584
Node not in G: mesh.D019584
Node not in G: cl.0000092
Node not in G: mesh.D003371
Node not in G: uniprot.A8B852
Node not in G: uniprot.Q968X7
Node not in G: hpo.0100497
Node not in G: mesh.D004776
Node not in G: mesh.D017382
Node not in G: hpo.0100497
Node not in G: mesh.D000534
Node not in G: mesh.C116664
Node not in G: mesh.C116664
Node not in mapping: MESH:D017319
Node not in G: mesh.D003371
Node not in G: cl.0000037
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.C007852
Node not in G: mesh.C007852
Node not in G: mesh.C007852
Node not in G: mesh.D013763
Node not in G: mesh.D013763
Node not in G: mesh.D033461
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: taxonomy.2
Node not in G: taxonomy.55193
Node not in G: taxonomy.5476
Node not in G: taxonomy.813
Node not in G: taxonomy.1747
Node not in G: taxonomy.562
Node not in G: taxonomy.813
Node not in G: mesh.D007752
Node not in G: uberon.0001796
Node not in G: mesh.D004487
Node not in G: mesh.D014812
Node not in G: mesh.D014812
Node not in G: mesh.D014812
Node not in G: mesh.D001171
Node not in G: mesh.D009128
Node not in G: interpro.CD15058
Node not in G: taxonomy.11676
Node not in G: mesh.D016055
Node not in G: reactome.R-HSA-8932339
Node not in G: mesh.D008077
Node not in G: mesh.D015878
Node not in G: taxonomy.11676
Node not in G: mesh.D006937
Node not in G: mesh.D008595
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: taxonomy.4751
Node not in G: mesh.D020250
Node not in G: mesh.D012912
Node not in G: mesh.D059350
Node not in G: mesh.D065446
Node not in G: chebi.17256
Node not in G: mesh.D006996
Node not in G: chebi.16933
Node not in G: mesh.D013928
Node not in G: mesh.D012912
Node not in G: mesh.D011537
Node not in G: mesh.C102295
Node not in G: mesh.C446479
Node not in G: mesh.C446479
Node not in G: mesh.C446479
Node not in G: mesh.D006937
Node not in G: taxonomy.5759
Node not in G: mesh.D011628
Node not in G: drugbank.
Node not in G: taxonomy.100942
Node not in G: taxonomy.6282
Node not in G: taxonomy.6293
Node not in G: drugbank.
Node not in G: mesh.D010146
Node not in G: mesh.D059350
Node not in G: mesh.D009999
Node not in G: mesh.D004487
Node not in G: mesh.C074679
Node not in G: chebi.50503
Node not in G: mesh.D012912
Node not in G: mesh.D011537
Node not in G: mesh.D011537
Node not in G: taxonomy.12059
Node not in G: drugbank.
Node not in G: mesh.D008075
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: taxonomy.4751
Node not in G: taxonomy.562
Node not in G: taxonomy.2
Node not in G: uniprot.Q5F5S1
Node not in G: taxonomy.76773
Node not in G: taxonomy.5519
Node not in G: mesh.D014987
Node not in G: uberon.0014892
Node not in G: mesh.D000787
Node not in G: uberon.0001796
Node not in G: chebi.26523
Node not in G: chebi.18059
Node not in G: chebi.16113
Node not in G: mesh.C047246
Node not in G: mesh.C064276
Node not in G: mesh.C064276
Node not in G: mesh.D005871
Node not in G: mesh.D013700
Node not in G: mesh.D001171
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: taxonomy.5855
Node not in G: mesh.D005744
Node not in G: mesh.D065446
Node not in G: mesh.D004247
Node not in G: mesh.D011538
Node not in G: mesh.D003371
Node not in G: chebi.18059
Node not in G: mesh.D001647
Node not in G: mesh.D001647
Node not in G: drugbank.DB19356
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: mesh.C072630
Node not in G: mesh.C072630
Node not in G: taxonomy.287
Node not in G: taxonomy.727
Node not in G: mesh.D005744
Node not in G: uberon.0000912
Node not in G: drugbank.
Node not in G: uberon.0000912
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: uberon.0000912
Node not in G: mesh.C036944
Node not in G: mesh.C036944
Node not in G: drugbank.DB09263
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: taxonomy.10335
Node not in G: pfam.PF11590
Node not in G: taxonomy.10335
Node not in G: taxonomy.76773
Node not in G: taxonomy.4751
Node not in G: taxonomy.5519
Node not in G: taxonomy.11103
Node not in G: taxonomy.10298
Node not in G: taxonomy.5691
Node not in G: mesh.C011010
Node not in G: taxonomy.11103
Node not in G: taxonomy.5820
Node not in G: interpro.PR001696
Node not in G: chebi.29108
Node not in G: mesh.C005312
Node not in G: interpro.IPR005884
Node not in G: interpro.IPR005884
Node not in G: interpro.IPR005884
Node not in G: interpro.IPR005884
Node not in G: interpro.IPR005884
Node not in G: interpro.IPR005884
Node not in G: interpro.IPR005884
Node not in G: mesh.D012912
Node not in G: taxonomy.12059
Node not in G: mesh.C059205
Node not in G: chebi.16134
Node not in G: chebi.16134
Node not in G: taxonomy.11676
Node not in G: mesh.D020078
Node not in G: mesh.D020078
Node not in G: mesh.D020078
Node not in G: mesh.D010146
Node not in G: chebi.15430
Node not in G: chebi.15430
Node not in G: mesh.C066340
Node not in G: mesh.D053202
Node not in G: drugbank.DB00088
Node not in G: drugbank.
Node not in G: chebi.23044
Node not in G: chebi.23044
Node not in G: chebi.23044
Node not in G: chebi.17376
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: taxonomy.237561
Node not in G: taxonomy.237561
Node not in G: mesh.D013923
Node not in G: drugbank.
Node not in G: chebi.18248
Node not in G: mesh.D002230
Node not in G: mesh.D002230
Node not in G: mesh.D002230
Node not in G: drugbank.DB08876
Node not in G: mesh.D011537
Node not in G: mesh.D012912
Node not in G: mesh.D011628
Node not in G: uberon.0001796
Node not in G: uberon.0001796
Node not in G: mesh.D012964
Node not in G: mesh.D000728
Node not in G: mesh.D019584
Node not in G: mesh.C000599709
Node not in G: taxonomy.1496
Node not in G: drugbank.
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D054680
Node not in G: mesh.D054680
Node not in G: mesh.D054680
Node not in G: mesh.D054680
Node not in G: mesh.D054680
Node not in G: chebi.8005
Node not in G: chebi.8005
Node not in G: chebi.30411
Node not in G: drugbank.
Node not in G: mesh.D010621
Node not in G: taxonomy.10566
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: chebi.16991
Node not in G: uberon.0000410
Node not in G: uberon.0000410
Node not in G: chebi.207229
Node not in G: drugbank.
Node not in G: mesh.C084588
Node not in G: mesh.C084588
Node not in G: mesh.C084588
Node not in G: mesh.D010146
Node not in G: taxonomy.5833
Node not in G: uniprot.Q8XET6
Node not in G: taxonomy.487
Node not in G: taxonomy.59201
Node not in G: taxonomy.1280
Node not in G: taxonomy.1280
Node not in G: taxonomy.781
Node not in G: taxonomy.780
Node not in G: mesh.D013107
Node not in G: taxonomy.1773
Node not in G: mesh.D054681
Node not in G: uberon.0010210
Node not in G: uberon.0010210
Node not in G: mesh.D003963
Node not in G: mesh.D004111
Node not in G: mesh.D004111
Node not in G: mesh.D004111
Node not in G: mesh.D004111
Node not in G: mesh.D004487
Node not in G: drugbank.
Node not in G: taxonomy.11103
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.C005804
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: interpro.IPR001460
Node not in G: mesh.D058427
Node not in G: mesh.D058427
Node not in G: mesh.D058427
Node not in G: mesh.D058427
Node not in G: mesh.D058427
Node not in G: mesh.D004247
Node not in G: chebi.8163
Node not in G: chebi.8163
Node not in G: chebi.8163
Node not in G: chebi.8163
Node not in G: mesh.D012912
Node not in G: mesh.D011537
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: mesh.D006947
Node not in G: mesh.D003371
Node not in G: mesh.D010665
Node not in G: mesh.D010665
Node not in G: mesh.D010665
Node not in G: mesh.D010665
Node not in G: mesh.D010665
Node not in G: mesh.D010665
Node not in G: mesh.D006473
Node not in G: taxonomy.624
Node not in G: taxonomy.1279
Node not in G: taxonomy.562
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: pfam.PF00449
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: chebi.18367
Node not in G: mesh.D006028
Node not in G: hpo.0031377
Node not in G: mesh.D008277
Node not in G: mesh.D008277
Node not in G: mesh.D008277
Node not in G: mesh.D008277
Node not in G: mesh.D008277
Node not in G: go.0000737
Node not in G: mesh.C089032
Node not in G: mesh.D005334
Node not in G: mesh.D003371
Node not in G: mesh.D004487
Node not in G: taxonomy.11103
Node not in G: mesh.D005334
Node not in G: uberon.0016553
Node not in G: mesh.D005100
Node not in G: mesh.D005100
Node not in G: mesh.D005100
Node not in G: uberon.0001796
Node not in G: mesh.C012255
Node not in G: mesh.D005334
Node not in G: taxonomy.237561
Node not in G: taxonomy.76773
Node not in G: taxonomy.237561
Node not in G: taxonomy.5551
Node not in G: taxonomy.5551
Node not in G: taxonomy.237561
Node not in G: mesh.D012912
Node not in G: mesh.D011537
Node not in G: chebi.36500
Node not in G: mesh.D005744
Node not in G: mesh.D043324
Node not in G: mesh.C039979
Node not in G: drugbank.
Node not in G: mesh.C030371
Node not in G: mesh.C030371
Node not in G: mesh.C415250
Node not in G: mesh.C003321
Node not in G: cl.0000101
Node not in G: cl.0000101
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D014839
Node not in G: mesh.D009325
Node not in G: mesh.D014549
Node not in G: mesh.D053158
Node not in G: mesh.D053159
Node not in G: mesh.D000069439
Node not in G: mesh.D000069439
Node not in G: taxonomy.10298
Node not in G: taxonomy.11103
Node not in G: mesh.D011453
Node not in G: taxonomy.11676
Node not in G: chebi.16991
Node not in G: mesh.D004247
Node not in G: cl.0000236
Node not in G: drugbank.
Node not in G: cl.0000236
Node not in G: mesh.D004247
Node not in G: go.0055072
Node not in G: mesh.D009325
Node not in G: mesh.D014839
Node not in G: drugbank.
Node not in G: mesh.D011538
Node not in G: taxonomy.1773
Node not in G: hpo.0031377
Node not in G: taxonomy.1280
Node not in G: taxonomy.573
Node not in G: taxonomy.39831
Node not in G: taxonomy.1313
Node not in G: taxonomy.1313
Node not in G: taxonomy.562
Node not in G: taxonomy.1280
Node not in G: taxonomy.562
Node not in G: mesh.D006937
Node not in G: taxonomy.11320
Node not in G: mesh.C102786
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: chebi.77035
Node not in G: chebi.77035
Node not in G: chebi.77035
Node not in G: mesh.C029620
Node not in G: mesh.D002614
Node not in G: drugbank.
Node not in G: taxonomy.562
Node not in G: taxonomy.39831
Node not in G: taxonomy.1485
Node not in G: taxonomy.543
Node not in G: taxonomy.1280
Node not in G: taxonomy.573
Node not in G: mesh.D003371
Node not in mapping: MESH:D054368
Node not in G: mesh.D000863
Node not in G: mesh.D000863
Node not in G: mesh.D000863
Node not in G: mesh.D000863
Node not in G: pfam.PF00905
Node not in G: pfam.PF00905
Node not in G: chebi.16991
Node not in G: chebi.16991
Node not in G: mesh.C026116
Node not in G: chebi.50919
Node not in G: chebi.50919
Node not in G: chebi.16991
Node not in G: drugbank.
Node not in G: drugbank.
Node not in G: taxonomy.562
Node not in G: chebi.4575
Node not in G: mesh.D012912
Node not in G: mesh.D011537
Node not in G: taxonomy.11676
Node not in G: mesh.C065180
Node not in G: taxonomy.1313
Node not in G: taxonomy.813
Node not in G: taxonomy.562
Node not in G: taxonomy.1280
Node not in G: taxonomy.1314
Node not in G: taxonomy.562
Node not in G: taxonomy.562
Node not in G: taxonomy.1313
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: taxonomy.11103
Node not in G: interpro.IPR006390
Node not in G: interpro.IPR006390
Node not in G: interpro.IPR006390
Node not in G: taxonomy.2
Node not in G: chebi.15356
Node not in G: chebi.17376
Node not in G: chebi.59683
Node not in G: mesh.D014811
Node not in G: mesh.D011537
Node not in G: taxonomy.287
Node not in G: mesh.C032302
Node not in G: mesh.D005963
Node not in G: chebi.18248
Node not in mapping: MESH:D054368
Node not in G: mesh.D002506
Node not in G: mesh.D002506
Node not in G: mesh.D002506
Node not in G: mesh.D002506
Node not in G: interpro.IPR001128﻿
Node not in G: chebi.27226
Node not in G: chebi.27226
Node not in G: mesh.D004295
Node not in G: mesh.D004295
Node not in G: mesh.D004295
Node not in G: mesh.D009128
Node not in G: mesh.D002303
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D004247
Node not in G: mesh.D000863
Node not in G: mesh.D011537
Node not in G: mesh.D005744
Node not in G: mesh.D005744
Node not in G: mesh.D009539
Node not in G: mesh.D000787
Node not in G: mesh.D013963
Node not in G: mesh.D014280
Node not in G: mesh.D008543
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in mapping: MESH:D012338
Node not in G: taxonomy.39824
Node not in G: mesh.D015878
Node not in G: drugbank.
Node not in G: drugbank.

In [16]:
val_path = [ind[i] for i in large_idx]

In [17]:
path_list = []
for i in large_idx: 
    path_nodes = []
    for j in ind[i]['nodes']:
        path_nodes.append(modified_data[j['id']])
    if len(path_nodes) > 2:
        path_list.append(path_nodes)

In [18]:
len(path_list)

405

In [ ]:
# # Define the file path where you want to save the resulting list
# file_path = 'val_path_large.json'

# # Save the selected_dicts list to a JSON file
# with open(file_path, 'w') as file:
#     json.dump(val_path, file)